blank_issues_enabled: false
contact_links:
  - name: Security Issue
    url: https://github.com/RMNCLDYO/create-codex/security/policy
    about: Please report security vulnerabilities here
  - name: Community Discussion
    url: https://github.com/RMNCLDYO/create-codex/discussions
    about: Ask questions and discuss ideas with the community